spring:
  application:
    name: mutation-testing-kata
  jpa:
    hibernate:
      ddl-auto:validate
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: superuser
    password: supersecret
